# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

critcpp <- function(a, b) {
    .Call('ClustVarLV_critcpp', PACKAGE = 'ClustVarLV', a, b)
}

mincpp <- function(a) {
    .Call('ClustVarLV_mincpp', PACKAGE = 'ClustVarLV', a)
}

