# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

critcpp <- function(a, b) {
    .Call('_ClustVarLV_critcpp', PACKAGE = 'ClustVarLV', a, b)
}

mincpp <- function(a) {
    .Call('_ClustVarLV_mincpp', PACKAGE = 'ClustVarLV', a)
}

powerEigen <- function(X) {
    .Call('_ClustVarLV_powerEigen', PACKAGE = 'ClustVarLV', X)
}

